const CardInfo2 = [
  {
    id: 1,
    name: 'Lucy Longhorn',
    time: '5 October at 14:00',
    profile: 'Friends',
    image: '',
    story: 'All subjects',
    image2: 'https://randomuser.me/api/portraits/women/67.jpg',
    image3: 'https://www.youtube.com/embed/qg5FDcEGHdw?autoplay=1&mute=1',
    posted: "Funny! 😀😀😀😀",
    height: '400px',
    LikedPost: "👍😀🥰 410",
    CommentCount: '6 comments'
  },
  {
    id: 2,
    name: 'Peter Piper',
    time: '1 h',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/2',
    story: 'Maths, English',
    image2: 'https://randomuser.me/api/portraits/men/57.jpg',
    image3: '',
    posted: "I have so many questions !!!!!!!! What is the world coming too?",
    height: '0px',
    LikedPost: "👍😀 32",
    CommentCount: '13 comments'
  },
  {
    id: 3,
    name: 'Michelle Gardener',
    time: '14mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/3',
    story: 'English, Geography',
    image2: 'https://randomuser.me/api/portraits/women/55.jpg',
    posted: "Never thought this was going to be that day.",
    height: '0px',
    LikedPost: "👍😮🎃 Tina read and 6 others",
    CommentCount: '1 comment',
  },
  {
    id: 4,
    name: 'Shane Jackson',
    time: '14 h',
    profile: 'Friends',
    image: '',
    story: 'History, Law',
    image2: 'https://randomuser.me/api/portraits/women/75.jpg',
    image3: 'https://www.youtube.com/embed/rSUytudGB8o?autoplay=1&mute=1',
    posted: "😜 I'm naked doing the unthinkable... ( ͡° ͜ʖ ͡°) ",
    height: '400px',
    LikedPost: "👍😮❤️ 410",
    CommentCount: '42 comments'
  },
  {
    id: 5,
    name: 'Kirk Douglas',
    time: '20 h',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/5',
    story: 'History, English, Law',
    image2: 'https://randomuser.me/api/portraits/men/50.jpg',
    posted: "ICYMI: Vader isn't the most powerful.",
    height: '0px',
    LikedPost: "👍😀❤️ Mel Williams and 6 others",
    CommentCount: '1 comment'
  },
  {
    id: 6,
    name: 'Libby Hatherton',
    time: '15mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/6',
    story: 'Law, English, Maths',
    image2: 'https://randomuser.me/api/portraits/women/41.jpg',
    posted: 'Great start to the week! Another happy customer. Work hard play harder!👀',
    height: '0px',
    LikedPost: '👍😂  Sissy Gant, Tony Johnson and 14 others',
    CommentCount: '3 comments'
  },
  {
    id: 7,
    name: 'Libby Hatherton',
    time: '15mins',
    profile: 'Friends',
    image: '',
    story: 'Law, English, Maths',
    image2: 'https://4.img-dpreview.com/files/p/E~C131x0S788x788T1200x1200~articles/2988339509/BlogHeader_150-1-1800x0-c-default_copy.jpeg',
    image3: 'https://images-tv.adobe.com/mpcv3/2625/5d450a50-fae9-4088-8122-8646872c8402_1596235121.1920x1080at3000_h264.mp4?autoplay=1&mute=1?autoplay=1&mute=1',
    posted: 'ADOBE PRODUCTS Learn new skills and be inspired in 350+ sessions.',
    height: '400px',
    LikedPost: "👍😀❤️ 1.2k",
    CommentCount: '98 comments  2 Shares'
  },
];

export default CardInfo2;
