const CardInfo = [
  {
    id: 1,
    name: 'Lucy Longhorn',
    time: '15mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/1',
    story: 'All subjects',
    image2: 'https://randomuser.me/api/portraits/women/67.jpg',
  },
  {
    id: 2,
    name: 'Peter Piper',
    time: '15mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/2',
    story: 'Maths, English',
    image2: 'https://randomuser.me/api/portraits/men/57.jpg',
  },
  {
    id: 3,
    name: 'Michelle Gardener',
    time: '15mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/3',
    story: 'English, Geography',
    image2: 'https://randomuser.me/api/portraits/women/55.jpg',
  },
  {
    id: 4,
    name: 'Shane Jackson',
    time: '15mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/4',
    story: 'History, Law',
    image2: 'https://randomuser.me/api/portraits/men/53.jpg',
  },
  {
    id: 5,
    name: 'Kirk Douglas',
    time: '15mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/5',
    story: 'History, English, Law',
    image2: 'https://randomuser.me/api/portraits/men/50.jpg',
  },
  {
    id: 6,
    name: 'Libby Hatherton',
    time: '15mins',
    profile: 'Friends',
    image: 'https://source.unsplash.com/random/6',
    story: 'Law, English, Maths',
    image2: 'https://randomuser.me/api/portraits/women/41.jpg',
  },
];

export default CardInfo;
